import Head from 'next/head';
import Navigation from 'sections/Navigation';
import Headlines from 'sections/Headlines';
import PopularNews from 'sections/PopularNews';
import Today from 'sections/Today';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';
import { wrapper } from 'redux/store';
import { popular } from 'redux/actions/actionCreator';
import { today } from 'redux/actions/actionCreator';

export default function Home() {
  // const news = useSelector(state => console.log(state.today))
  return (
    <div>
      <Head>
        <title>The new york times</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Headlines />
      <PopularNews />
      <Today />
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async () => {
      await store.dispatch(popular())
      await store.dispatch(today())
    }
)