export const POPULAR_SUCCESS = "POPULAR_SUCCESS";
export const POPULAR_FAILED = "POPULAR_FAILED";
export const POPULAR_LOADING = "POPULAR_LOADING";
export const TODAY_SUCCESS = "TODAY_SUCCESS";
export const TODAY_FAILED = "TODAY_FAILED";
export const TODAY_LOADING = "TODAY_LOADING";




export const CLEAR_ERRORS = "CLEAR_ERRORS";